/*
 * This file is generated by jOOQ.
 */
package com.ere.consumer.usersservice.domain.jooq.tables.records;


import com.ere.consumer.usersservice.domain.jooq.tables.Clients;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.processing.Generated;


/**
 * client users
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClientsRecord extends UpdatableRecordImpl<ClientsRecord> implements Record5<Integer, String, String, String, String> {

    private static final long serialVersionUID = 183448598;

    /**
     * Setter for <code>dbo.clients.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>dbo.clients.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>dbo.clients.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>dbo.clients.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>dbo.clients.username</code>.
     */
    public void setUsername(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>dbo.clients.username</code>.
     */
    public String getUsername() {
        return (String) get(2);
    }

    /**
     * Setter for <code>dbo.clients.password</code>.
     */
    public void setPassword(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>dbo.clients.password</code>.
     */
    public String getPassword() {
        return (String) get(3);
    }

    /**
     * Setter for <code>dbo.clients.clientid</code>.
     */
    public void setClientid(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>dbo.clients.clientid</code>.
     */
    public String getClientid() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, String, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, String, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Clients.CLIENTS.ID;
    }

    @Override
    public Field<String> field2() {
        return Clients.CLIENTS.NAME;
    }

    @Override
    public Field<String> field3() {
        return Clients.CLIENTS.USERNAME;
    }

    @Override
    public Field<String> field4() {
        return Clients.CLIENTS.PASSWORD;
    }

    @Override
    public Field<String> field5() {
        return Clients.CLIENTS.CLIENTID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getUsername();
    }

    @Override
    public String component4() {
        return getPassword();
    }

    @Override
    public String component5() {
        return getClientid();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getUsername();
    }

    @Override
    public String value4() {
        return getPassword();
    }

    @Override
    public String value5() {
        return getClientid();
    }

    @Override
    public ClientsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ClientsRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public ClientsRecord value3(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public ClientsRecord value4(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public ClientsRecord value5(String value) {
        setClientid(value);
        return this;
    }

    @Override
    public ClientsRecord values(Integer value1, String value2, String value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClientsRecord
     */
    public ClientsRecord() {
        super(Clients.CLIENTS);
    }

    /**
     * Create a detached, initialised ClientsRecord
     */
    public ClientsRecord(Integer id, String name, String username, String password, String clientid) {
        super(Clients.CLIENTS);

        set(0, id);
        set(1, name);
        set(2, username);
        set(3, password);
        set(4, clientid);
    }
}
