server:
  port: 8081

spring:
  datasource:
    master:
      jdbc-url: jdbc:postgresql://localhost:5432/public
      username: postgres
      password: postgres
      driverClassName: org.postgresql.Driver
    hikari:
      maximum-pool-size: 50
  profiles:
    active: native

