/*
 * This file is generated by jOOQ.
 */
package com.ere.consumer.usersservice.domain.jooq;


import com.ere.consumer.usersservice.domain.jooq.tables.Cars;
import com.ere.consumer.usersservice.domain.jooq.tables.Clients;
import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import javax.annotation.processing.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Dbo extends SchemaImpl {

    private static final long serialVersionUID = -1545152684;

    /**
     * The reference instance of <code>dbo</code>
     */
    public static final Dbo DBO = new Dbo();

    /**
     * The table <code>dbo.cars</code>.
     */
    public final Cars CARS = Cars.CARS;

    /**
     * client users
     */
    public final Clients CLIENTS = Clients.CLIENTS;

    /**
     * No further instances allowed
     */
    private Dbo() {
        super("dbo", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.CARS_ID_SEQ,
            Sequences.CLIENTS_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Cars.CARS,
            Clients.CLIENTS);
    }
}
