/*
 * This file is generated by jOOQ.
 */
package com.ere.consumer.usersservice.domain.jooq;


import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all sequences in dbo
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>dbo.cars_id_seq</code>
     */
    public static final Sequence<Integer> CARS_ID_SEQ = new SequenceImpl<Integer>("cars_id_seq", Dbo.DBO, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>dbo.clients_id_seq</code>
     */
    public static final Sequence<Integer> CLIENTS_ID_SEQ = new SequenceImpl<Integer>("clients_id_seq", Dbo.DBO, org.jooq.impl.SQLDataType.INTEGER.nullable(false));
}
